[package]
name = "rustbook"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "0500structs"
path = "src/0500structs.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
