[package]
name = "rustbook"
version = "0.1.0"
edition = "2021"

#[[bin]]
#name = "0600enums"
#path = "src/0600enums.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
